name = "avd-base"
base = true

[manifest]
source = "local"
url = "https://android.googlesource.com/kernel/manifest"
minimal = true

[build]
system = "kleaf"
target = "//common-modules/virtual-device:virtual_device_{arch}_dist"
warmup_target = "//common:kernel_{arch}"
dist_flag = "dist_dir"
lto = "thin"

[cache]
repo_dir = "repo"
bazel_dir = "bazel"
ccache_dir = "ccache"

[workspace]
source_dir = "android-kernel"
