name = "avd-android15-6.6-arm64"

[manifest]
source = "local"
url = "https://android.googlesource.com/kernel/manifest"
branch = "common-android15-6.6"
path = "../../manifests/avd/avd-android-15-6.6_arm64.xml"
minimal = true

[build]
system = "kleaf"
target = "//common-modules/virtual-device:virtual_device_{arch}_dist"
warmup_target = "//common-modules/virtual-device:virtual_device_{arch}"
dist_dir = "avd/android15-6.6-arm64"
dist_flag = "dist_dir"
arch = "aarch64"
lto = "thin"

[cache]
repo_dir = "repo"
bazel_dir = "bazel"
ccache_dir = "ccache"

[workspace]
source_dir = "android-kernel"
metadata_dir = ".gki-builder"
