name = "avd-base"
base = true

[repo]
url = "https://android.googlesource.com/kernel/manifest"
minimal = true

[kleaf]
target = "//common-modules/virtual-device:virtual_device_{arch}_dist"
warmup_target = "//common:kernel_{arch}"
dist_flag = "dist_dir"
lto = "thin"
