name = "kleaf-base"
base = true

[repo]
url = "https://android.googlesource.com/kernel/manifest"
file = "default.xml"
minimal = true
autodetect_deprecated = true

[kleaf]
target = "//common:kernel_{arch}_dist"
warmup_target = "//common:kernel_{arch}"
dist_flag = "dist_dir"
arch = "aarch64"
lto = "thin"
