name = "legacy-base"
base = true

[repo]
url = "https://android.googlesource.com/kernel/manifest"
file = "default.xml"
minimal = true
autodetect_deprecated = true

[legacy]
legacy_config = "common/build.config.gki.{arch}"
arch = "aarch64"
lto = "thin"
